click/urls.py
"""
click URL Configuration
"""
from django.urls import path
from . import views

app_name = 'click'
urlpatterns = [
    path('', views.index, name='index'),
    path('categories/', views.categories, name='categories'),
    path('services/<int:id>', views.services_page, name='services'),
    path('service/<int:id>', views.service_page, name='service'),
    path('book-service/<int:id>', views.book_service, name='book-service'),
    path('book_service_insert/<int:id>', views.book_service_insert, name='book_service_insert'),
    path('about/', views.about, name='about'),
    path('login/', views.loginView, name='login'),
    path('contact/', views.contact, name='contact'),
    path('auth/login/', views.authLogin, name='auth-login'),
    path('auth/signup/', views.authSignup, name='auth-signup'),
    path('auth/logout/', views.authLogout, name='auth-logout'),
    path('user/', views.user, name='user'),
    path('user/dashboard', views.userDashboard, name='user-dashboard'),
    path('user/bookings', views.userBooking, name='user-bookings'),
    path('user/profile', views.userProfile, name='user-profile'),
    path('user/reviews', views.userReviews, name='user-reviews'),
    path('staff/', views.staff, name='staff'),
    path('staff/dashboard', views.staffDashboard, name='staff-dashboard'),
    path('staff/bookings', views.staffBooking, name='staff-bookings'),
    path('staff/profile', views.staffProfile, name='staff-profile'),
    path('dpupdate', views.update_dp, name='dpupdate'),
    path('cancel-booking', views.cancel_booking, name='cancel_booking'),
    path('status-update', views.booking_status, name='booking_status'),
    path('booking-comment', views.booking_comment, name='booking_comment'),
    
]

oneclick/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('click.urls')),
    path('payment/', include('payments.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns=urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

click/models.py
from django.db import models
from django.db import connections
from django.contrib.auth.models import User
from PIL import Image
from django.utils.timezone import now


class category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    featured = models.BooleanField(default=False)
    image = models.ImageField(upload_to='category', default='SOME STRING')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Categories"


class service(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='service', default='SOME STRING')
    description = models.TextField()
    feature = models.CharField(max_length=200)
    price = models.IntegerField(default=10)
    category = models.ForeignKey(category,  on_delete=models.CASCADE)
    featured = models.BooleanField(default=False)
    visible = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class booking(models.Model):
    booking_date = models.DateTimeField(auto_now_add=True, editable=False)
    date = models.DateField(default=now,blank=True, null=True)
    time = models.TimeField(default=now)
    location = models.TextField()
    phn = models.BigIntegerField(verbose_name="Phone Number")
    staff = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='staff', null=True, blank=True)
    status = models.CharField(max_length=256, default='Pending', choices=[('Pending', 'Pending'), (
        'Staff assigned', 'Staff assigned'), ('In progress', 'In progress'), ('Completed', 'Completed'), ('Canceled', 'Canceled')])
    service = models.ForeignKey(service, on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='user')
    reason= models.TextField(null=True,blank=True)
    payment_id = models.TextField(default='nil')

    def __str__(self):
        return f"{self.user.first_name} - {self.service.title}"



class comments(models.Model):
    comment = models.TextField()
    rating = models.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    service = models.ForeignKey(service, on_delete=models.CASCADE)
    booking = models.OneToOneField(booking, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Review"

class profile(models.Model):
    image = models.ImageField(upload_to='profile', default='profile/profile.png')
    mobile = models.BigIntegerField(verbose_name="Phone Number")
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob=models.DateField(default=now,blank=True, null=True)
    

click/views.py
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.db.models.aggregates import Avg
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from .models import *
from django.db.models import Count
from django.contrib import messages
import stripe

# Test Functions


def not_auth(user):
    return not user.is_authenticated


def is_staff(user):
    return user.is_staff


# Create your views here.
def index(request):
    categories = category.objects.filter(
        featured=1).annotate(service_count=Count('service'))
    services = service.objects.filter(featured=1)
    return render(request, 'index.html', {'categories': categories, 'services': services})


def categories(request):
    categories = category.objects.annotate(service_count=Count('service'))
    return render(request, 'categories.html', {'categories': categories})


def services_page(request, id):
    services = service.objects.annotate(avg_rating=Avg('comments__rating')).filter(category=id)
    services_count = len(services)
    return render(request, 'services.html', {'services': services, 'services_count': services_count})


def service_page(request, id):
    serviceData = service.objects.annotate(
        avg_rating=Avg('comments__rating')).get(id=id)
    reviews = comments.objects.filter(service=serviceData.id)
    relateds = service.objects.annotate(avg_rating=Avg('comments__rating')).filter(
        category=serviceData.category.id).exclude(id=serviceData.id)
    return render(request, 'service.html', {'service': serviceData, 'reviews': reviews, 'relateds': relateds})


def book_service(request, id):
    if request.user.is_anonymous:
        return redirect('click:login')
    service_ = service.objects.get(id=id)
    return render(request, 'book-service.html', {'service': service_})


def book_service_insert(request, id):
    serviceData = service.objects.get(id=id)
    post = booking()
    post.date = request.POST.get('date')
    post.time = request.POST.get('time')
    post.location = request.POST.get('location')
    post.phn = request.POST.get('phone')
    post.service = serviceData
    post.user = request.user
    post.save()
    # messages.success(request, 'Booking Success')

    domain_url = 'http://localhost:8000/payment/'
    stripe.api_key = settings.STRIPE_SECRET_KEY
    try:
        checkout_session = stripe.checkout.Session.create(
            # new
            client_reference_id=request.user.id if request.user.is_authenticated else None,
            success_url=domain_url + \
            'success?session_id={CHECKOUT_SESSION_ID}',
            cancel_url=domain_url + 'cancelled/',
            payment_method_types=['card'],
            mode='payment',
            line_items=[
                {
                    'name': serviceData.title,
                    'quantity': 1,
                    'currency': 'inr',
                    'amount': str(serviceData.price) +'00',
                }
            ]
        )
        post.payment_id = checkout_session['payment_intent']
        post.save()
        request.session['checkout_session'] = checkout_session['id']
        # return JsonResponse({'sessionId': checkout_session['id']})
        return redirect('payments:payments')
    except Exception as e:
        print(str(e))
        # return JsonResponse({'error': str(e)})
        return redirect('/payment/cancelled/')


def cancel_booking(request):
    book = booking.objects.get(id=request.POST.get('booking_id'))
    book.reason = request.POST.get('reason')
    book.status = 'Canceled'
    book.save()
    messages.warning(request, 'Booking Canceled')
    if request.user.is_staff:
        return redirect('click:staff-bookings')
    else:
        return redirect('click:user-bookings')


def booking_status(request):
    book = booking.objects.get(id=request.POST.get('booking_id'))
    book.status = request.POST.get('status')
    book.save()
    messages.success(request, 'Status updated')
    if request.user.is_staff:
        return redirect('click:staff-bookings')
    else:
        return redirect('click:user-bookings')


def booking_comment(request):
    book = booking.objects.get(id=request.POST.get('booking_id'))
    serv = service.objects.get(id=request.POST.get('service_id'))
    comm = comments()
    comm.comment = request.POST.get('comment')
    comm.rating = request.POST.get('rate')
    comm.service = serv
    comm.booking = book
    comm.user = request.user
    comm.save()
    messages.success(request, 'Rating Posted Successfully')
    return redirect('click:user-bookings')


@user_passes_test(not_auth, 'click:user-dashboard', redirect_field_name='')
def loginView(request):
    return render(request, 'login.html')


def about(request):
    return render(request, 'about.html')


def contact(request):
    return render(request, 'contact.html')


# Authentication here.
def authLogin(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        if(user.is_superuser):
            return redirect('admin:index')
        else:
            return redirect('click:index')
    else:
        messages.error(request, 'Error Login')
        return redirect('click:login')


def authSignup(request):
    try:
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        user = User.objects.create_user(username, email, password)
        user.first_name = first_name
        user.last_name = last_name
        user.save()
        profil = profile()
        profil.dob = request.POST['date_of_birth']
        profil.mobile = request.POST['mob']
        profil.user = user
        profil.save()
        if user:
            login(request, user)
            return redirect('click:index')
        else:
            messages.error(request, 'Error Signup')
            return redirect('click:login')
    except:
        messages.error(request, 'Error Signup')
        return redirect('click:login')


def update_dp(request):
    pro = profile.objects.get(id=request.user.profile.id)
    pro.image = request.FILES.get('img')
    pro.save()
    if request.user.is_staff:
        return redirect('click:staff-profile')
    else:
        return redirect('click:user-profile')


def authLogout(request):
    logout(request)
    return redirect('click:index')


# User Routes
@login_required(login_url='click:login', redirect_field_name='')
def user(request):
    return redirect('click:user-dashboard')


@login_required(login_url='click:login', redirect_field_name='')
def userDashboard(request):
    bookings = booking.objects.filter(user=request.user)
    reviews = comments.objects.filter(user=request.user)
    bookings_count = len(bookings)
    reviews_count = len(reviews)
    return render(request, 'user/user-dashboard.html',{'bookings_count':bookings_count,'reviews_count':reviews_count})


@login_required(login_url='click:login', redirect_field_name='')
def userBooking(request):
    bookings = booking.objects.filter(user=request.user).order_by('-id')
    return render(request, 'user/user-booking.html', {'bookings': bookings})


@login_required(login_url='click:login', redirect_field_name='')
def userProfile(request):
    return render(request, 'user/user-profile.html')


@login_required(login_url='click:login', redirect_field_name='')
def userReviews(request):
    reviews = comments.objects.filter(user=request.user)
    return render(request, 'user/user-reviews.html', {'reviews': reviews})


# Staff Routes
@login_required(login_url='click:login', redirect_field_name='')
def staff(request):
    return redirect('click:staff-dashboard')


@login_required(login_url='click:login', redirect_field_name='')
def staffDashboard(request):
    bookings = booking.objects.filter(staff=request.user)
    bookings_count = len(bookings)
    return render(request, 'staff/staff-dashboard.html',{'bookings_count':bookings_count})


@login_required(login_url='click:login', redirect_field_name='')
def staffBooking(request):
    bookings = booking.objects.filter(staff=request.user).order_by('-id')
    return render(request, 'staff/staff-booking.html', {'bookings': bookings})


@login_required(login_url='click:login', redirect_field_name='')
def staffProfile(request):
    return render(request, 'staff/staff-profile.html')

click/templates/includes/footer.html
<!-- Footer -->
<footer class="footer">

    <!-- Footer Top -->
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <!-- Footer Widget -->
                    <div class="footer-widget footer-menu">
                        <h2 class="footer-title">Quick Links </h2>
                        <ul>
                            <li>
                                <a href="about-us.html">About Us</a>
                            </li>
                            <li>
                                <a href="contact-us.html">Contact Us</a>
                            </li>
                            <li>
                                <a href="faq.html">Faq</a>
                            </li>
                            <li>
                                <a href="#">Help</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /Footer Widget -->
                </div>
                <div class="col-lg-3 col-md-6">
                    <!-- Footer Widget -->
                    <div class="footer-widget footer-menu">
                        <h2 class="footer-title">Categories</h2>
                        <ul>
                            <li>
                                <a href="search.html">Computer</a>
                            </li>
                            <li>
                                <a href="search.html">Interior</a>
                            </li>
                            <li>
                                <a href="search.html">Car Wash</a>
                            </li>
                            <li>
                                <a href="search.html">Cleaning</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /Footer Widget -->
                </div>
                <div class="col-lg-3 col-md-6">
                    <!-- Footer Widget -->
                    <div class="footer-widget footer-contact">
                        <h2 class="footer-title">Contact Us</h2>
                        <div class="footer-contact-info">
                            <div class="footer-address">
                                <span><i class="far fa-building"></i></span>
                                <p>367 Hillcrest Lane, Irvine, California, United States</p>
                            </div>
                            <p><i class="fas fa-headphones"></i> 321 546 8764</p>
                            <p class="mb-0"><i class="fas fa-envelope"></i> OneClick@example.com</p>
                        </div>
                    </div>
                    <!-- /Footer Widget -->
                </div>
                <div class="col-lg-3 col-md-6">
                    <!-- Footer Widget -->
                    <div class="footer-widget">
                        <h2 class="footer-title">Follow Us</h2>
                        <div class="social-icon">
                            <ul>
                                <li>
                                    <a href="#" target="_blank"><i class="fab fa-facebook-f"></i> </a>
                                </li>
                                <li>
                                    <a href="#" target="_blank"><i class="fab fa-twitter"></i> </a>
                                </li>
                                <li>
                                    <a href="#" target="_blank"><i class="fab fa-youtube"></i></a>
                                </li>
                                <li>
                                    <a href="#" target="_blank"><i class="fab fa-google"></i></a>
                                </li>
                            </ul>
                        </div>
                        <div class="subscribe-form">
                            <input type="email" class="form-control" placeholder="Enter your email">
                            <button type="submit" class="btn footer-btn">
                                <i class="fas fa-paper-plane"></i>
                            </button>
                        </div>
                    </div>
                    <!-- /Footer Widget -->
                </div>
            </div>
        </div>
    </div>
    <!-- /Footer Top -->

    <!-- Footer Bottom -->
    <div class="footer-bottom">
        <div class="container">
            <!-- Copyright -->
            <div class="copyright">
                <div class="row">
                    <div class="col-md-6 col-lg-6">
                        <div class="copyright-text">
                            <p class="mb-0">&copy; 2020 <a href="/">OneClick</a>. All rights
                                reserved.</p>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-6">
                        <!-- Copyright Menu -->
                        <div class="copyright-menu">
                            <ul class="policy-menu">
                                <li>
                                    <a href="term-condition.html">Terms and Conditions</a>
                                </li>
                                <li>
                                    <a href="privacy-policy.html">Privacy</a>
                                </li>
                            </ul>
                        </div>
                        <!-- /Copyright Menu -->
                    </div>
                </div>
            </div>
            <!-- /Copyright -->
        </div>
    </div>
    <!-- /Footer Bottom -->

</footer>
<!-- /Footer -->

click/templates/includes/header.html
<!-- Header -->
<header class="header">
    <nav class="navbar navbar-expand-lg header-nav">
        <div class="navbar-header">
            <a id="mobile_btn" href="javascript:void(0);">
                <span class="bar-icon">
                    <span></span>
                    <span></span>
                    <span></span>
                </span>
            </a>
            <a href="{% url 'click:index' %}" class="navbar-brand logo">
                <img src="{% static 'img/logo.png' %}" class="img-fluid" alt="Logo">
            </a>
            <a href="{% url 'click:index' %}" class="navbar-brand logo-small">
                <img src="{% static 'img/logo-icon.png' %}" class="img-fluid" alt="Logo">
            </a>
        </div>
        <div class="main-menu-wrapper">
            <div class="menu-header">
                <a href="{% url 'click:index' %}" class="menu-logo">
                    <img src="{% static 'img/logo.png' %}" class="img-fluid" alt="Logo">
                </a>
                <a id="menu_close" class="menu-close" href="javascript:void(0);"> <i class="fas fa-times"></i></a>
            </div>
            <ul class="main-nav">
                <li class="active">
                    <a href="{% url 'click:index' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'click:about' %}">About</a>
                </li>
                <li>
                    <a href="{% url 'click:categories' %}">Categories</a>
                </li>
                {% comment %} <li class="has-submenu">
                    <a href="provider-dashboard.html">Providers</a>
                    <ul class="submenu">
                        <li><a href="provider-dashboard.html">Dashboard</a></li>
                        <li><a href="my-services.html">Services</a></li>
                        <li><a href="provider-bookings.html">Bookings</a></li>
                        <li><a href="provider-settings.html">Profile Settings</a></li>
                        <li><a href="provider-wallet.html">Wallet</a></li>
                        <li><a href="provider-subscription.html">Subscription</a></li>
                        <li><a href="provider-availability.html">Availability</a></li>
                        <li><a href="provider-reviews.html">Reviews</a></li>
                        <li><a href="provider-payment.html">Payment</a></li>
                    </ul>
                </li> {% endcomment %}
                {% comment %} <li class="has-submenu">
                    <a href="#">Pages <i class="fas fa-chevron-down"></i></a>
                    <ul class="submenu">
                        <li><a href="search.html">Search</a></li>
                        <li><a href="service-details.html">Service Details</a></li>
                        <li><a href="add-service.html">Add Service</a></li>
                        <li><a href="edit-service.html">Edit Service</a></li>
                        <li><a href="chat.html">Chat</a></li>
                        <li><a href="notifications.html">Notifications</a></li>
                        <li><a href="about-us.html">About Us</a></li>
                        <li><a href="contact-us.html">Contact Us</a></li>
                        <li><a href="faq.html">Faq</a></li>
                        <li><a href="#">Terms & Conditions</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                    </ul>
                </li> {% endcomment %}
                {% comment %} <li>
                    <a href="admin/index.html" target="_blank">Admin</a>
                </li> {% endcomment %}
                <li>
                    <a href="{% url 'click:contact' %}">Contact</a>
                </li>
                {% if user.is_authenticated %}
                <li class="has-submenu">
                    <a href="javascript:void(0);">Welcome {{ user.first_name }} <i class="fas fa-chevron-down"></i></a>
                    <ul class="submenu">
                        {% if user.is_staff %}
                        <li><a href="{% url 'click:staff-dashboard' %}">Dashboard</a></li>
                        <li><a href="{% url 'click:staff-bookings' %}">Bookings</a></li>
                        <li><a href="{% url 'click:staff-profile' %}">Profile Settings</a></li>
                        <li><a href="{% url 'click:auth-logout' %}">Logout</a></li>
                        {% else %}

                        <li><a href="{% url 'click:user-dashboard' %}">Dashboard</a></li>
                        <li><a href="{% url 'click:user-bookings' %}">Bookings</a></li>
                        <li><a href="{% url 'click:user-profile' %}">Profile Settings</a></li>
                        <li><a href="{% url 'click:user-reviews' %}">Reviews</a></li>
                        <li><a href="{% url 'click:auth-logout' %}">Logout</a></li>
                        {% endif %}
                    </ul>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'click:login' %}">Login</a>
                </li>
                {% endif %}
                {% comment %} <li>
                    <a href="javascript:void(0);" data-toggle="modal" data-target="#provider-register">Become a
                        Professional</a>
                </li>
                <li>
                    <a href="javascript:void(0);" data-toggle="modal" data-target="#user-register">Become a User</a>
                </li> {% endcomment %}
            </ul>
        </div>
        {% comment %} <ul class="nav header-navbar-rht">
            <li class="nav-item">
                <a class="nav-link header-login" href="javascript:void(0);" data-toggle="modal"
                    data-target="#login_modal">Login</a>
            </li>
        </ul> {% endcomment %}
    </nav>
</header>
<!-- /Header -->

click/templates/includes/messages.html
{% if messages %}
{% for message in messages %}

{% if message.tags == 'success' %}
<script>
var message = "{{ message }}"
$( document ).ready(function() {
    alertify.success(message); 
});
</script>
{% endif %}

{% if message.tags == 'warning' %}
<script>
var message = "{{ message }}"
$( document ).ready(function() {
    alertify.warning(message); 
});
</script>
{% endif %}

{% if message.tags == 'error' %}
<script>
var message = "{{ message }}"
$( document ).ready(function() {
    alertify.error(message); 
});
</script>
{% endif %}
{% endfor %}
{% endif %}

click/templates/includes/staff-dashboard-sidebar.html
<div class="col-xl-3 col-md-4 theiaStickySidebar">
    <div class="mb-4">
        <div class="d-sm-flex flex-row flex-wrap text-center text-sm-left align-items-center">
            <img alt="profile image" src="{{user.profile.image.url}}" class="avatar-lg rounded-circle">
            <div class="ml-sm-3 ml-md-0 ml-lg-3 mt-2 mt-sm-0 mt-md-2 mt-lg-0">
                <h6 class="mb-0">{{ user.first_name }} {{ user.last_name }}</h6>
                <p class="text-muted mb-0">Member Since <br/>{{ user.date_joined|date:'M d, Y'}}</p>
            </div>
        </div>
    </div>
    <div class="widget settings-menu">
        <ul role="tablist" class="nav nav-tabs">
            <li class="nav-item current">
                <a href="{% url 'click:staff-dashboard' %}" class="nav-link">
                    <i class="fas fa-chart-line"></i> <span>Dashboard</span>
                </a>
            </li>
            <li class="nav-item current">
                <a href="{% url 'click:staff-bookings' %}" class="nav-link">
                    <i class="far fa-calendar-check"></i> <span>Booking List</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'click:staff-profile' %}" class="nav-link">
                    <i class="far fa-user"></i> <span>Profile</span>
                </a>
            </li>
        </ul>
    </div>
</div>

click/templates/includes/user-dashboard-sidebar.html
<div class="col-xl-3 col-md-4 theiaStickySidebar">
    <div class="mb-4">
        <div class="d-sm-flex flex-row flex-wrap text-center text-sm-left align-items-center">
            <img alt="profile image" src="{{user.profile.image.url}}" class="avatar-lg rounded-circle">
            <div class="ml-sm-3 ml-md-0 ml-lg-3 mt-2 mt-sm-0 mt-md-2 mt-lg-0">
                <h6 class="mb-0">{{ user.first_name }} {{ user.last_name }}</h6>
                <p class="text-muted mb-0">Member Since <br/>{{ user.date_joined|date:'M d, Y'}}</p>
            </div>
        </div>
    </div>
    <div class="widget settings-menu">
        <ul role="tablist" class="nav nav-tabs">
            <li class="nav-item current">
                <a href="{% url 'click:user-dashboard' %}" class="nav-link">
                    <i class="fas fa-chart-line"></i> <span>Dashboard</span>
                </a>
            </li>
            <li class="nav-item current">
                <a href="{% url 'click:user-bookings' %}" class="nav-link">
                    <i class="far fa-calendar-check"></i> <span>My Bookings</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'click:user-profile' %}" class="nav-link">
                    <i class="far fa-user"></i> <span>Profile</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'click:user-reviews' %}" class="nav-link">
                    <i class="far fa-star"></i> <span>Reviews</span>
                </a>
            </li>
        </ul>
    </div>
</div>

click/templates/includes/works.html
<section class="how-work">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="heading howitworks">
                    <h2>How It Works</h2>
                    {% comment %} <span>Aliquam lorem ante, dapibus in, viverra quis</span> {% endcomment %}
                </div>
                <div class="howworksec">
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="howwork">
                                <div class="iconround">
                                    <div class="steps">01</div>
                                    <img src="{% static 'img/icon-1.png' %}" alt="">
                                </div>
                                <h3>Find the Service</h3>
                                {% comment %} <p>Aliquam lorem ante, dapibus in, viverra quis, feugiat Phasellus viverra nulla ut
                                    metus varius laoreet.</p> {% endcomment %}
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="howwork">
                                <div class="iconround">
                                    <div class="steps">02</div>
                                    <img src="{% static 'img/icon-2.png' %}" alt="">
                                </div>
                                <h3>Book the Service</h3>
                                {% comment %} <p>Aliquam lorem ante, dapibus in, viverra quis, feugiat Phasellus viverra nulla ut
                                    metus varius laoreet.</p> {% endcomment %}
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="howwork">
                                <div class="iconround">
                                    <div class="steps">03</div>
                                    <img src="{% static 'img/icon-3.png' %}" alt="">
                                </div>
                                <h3>Our Staff at your Doorstep</h3>
                                {% comment %} <p>Aliquam lorem ante, dapibus in, viverra quis, feugiat Phasellus viverra nulla ut
                                    metus varius laoreet.</p> {% endcomment %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>