click/urls.py
"""
click URL Configuration
"""
from django.urls import path
from . import views

app_name = 'click'
urlpatterns = [
    path('', views.index, name='index'),
    path('categories/', views.categories, name='categories'),
    path('services/<int:id>', views.services_page, name='services'),
    path('service/<int:id>', views.service_page, name='service'),
    path('book-service/<int:id>', views.book_service, name='book-service'),
    path('book_service_insert/<int:id>', views.book_service_insert, name='book_service_insert'),
    path('about/', views.about, name='about'),
    path('login/', views.loginView, name='login'),
    path('contact/', views.contact, name='contact'),
    path('auth/login/', views.authLogin, name='auth-login'),
    path('auth/signup/', views.authSignup, name='auth-signup'),
    path('auth/logout/', views.authLogout, name='auth-logout'),
    path('user/', views.user, name='user'),
    path('user/dashboard', views.userDashboard, name='user-dashboard'),
    path('user/bookings', views.userBooking, name='user-bookings'),
    path('user/profile', views.userProfile, name='user-profile'),
    path('user/reviews', views.userReviews, name='user-reviews'),
    path('staff/', views.staff, name='staff'),
    path('staff/dashboard', views.staffDashboard, name='staff-dashboard'),
    path('staff/bookings', views.staffBooking, name='staff-bookings'),
    path('staff/profile', views.staffProfile, name='staff-profile'),
    path('dpupdate', views.update_dp, name='dpupdate'),
    path('cancel-booking', views.cancel_booking, name='cancel_booking'),
    path('status-update', views.booking_status, name='booking_status'),
    path('booking-comment', views.booking_comment, name='booking_comment'),
    
]

oneclick/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('click.urls')),
    path('payment/', include('payments.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns=urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

click/models.py
from django.db import models
from django.db import connections
from django.contrib.auth.models import User
from PIL import Image
from django.utils.timezone import now


class category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    featured = models.BooleanField(default=False)
    image = models.ImageField(upload_to='category', default='SOME STRING')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Categories"


class service(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='service', default='SOME STRING')
    description = models.TextField()
    feature = models.CharField(max_length=200)
    price = models.IntegerField(default=10)
    category = models.ForeignKey(category,  on_delete=models.CASCADE)
    featured = models.BooleanField(default=False)
    visible = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class booking(models.Model):
    booking_date = models.DateTimeField(auto_now_add=True, editable=False)
    date = models.DateField(default=now,blank=True, null=True)
    time = models.TimeField(default=now)
    location = models.TextField()
    phn = models.BigIntegerField(verbose_name="Phone Number")
    staff = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='staff', null=True, blank=True)
    status = models.CharField(max_length=256, default='Pending', choices=[('Pending', 'Pending'), (
        'Staff assigned', 'Staff assigned'), ('In progress', 'In progress'), ('Completed', 'Completed'), ('Canceled', 'Canceled')])
    service = models.ForeignKey(service, on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='user')
    reason= models.TextField(null=True,blank=True)
    payment_id = models.TextField(default='nil')

    def __str__(self):
        return f"{self.user.first_name} - {self.service.title}"



class comments(models.Model):
    comment = models.TextField()
    rating = models.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    service = models.ForeignKey(service, on_delete=models.CASCADE)
    booking = models.OneToOneField(booking, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Review"

class profile(models.Model):
    image = models.ImageField(upload_to='profile', default='profile/profile.png')
    mobile = models.BigIntegerField(verbose_name="Phone Number")
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob=models.DateField(default=now,blank=True, null=True)
    

click/views.py
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.db.models.aggregates import Avg
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from .models import *
from django.db.models import Count
from django.contrib import messages
import stripe

# Test Functions


def not_auth(user):
    return not user.is_authenticated


def is_staff(user):
    return user.is_staff


# Create your views here.
def index(request):
    categories = category.objects.filter(
        featured=1).annotate(service_count=Count('service'))
    services = service.objects.filter(featured=1)
    return render(request, 'index.html', {'categories': categories, 'services': services})


def categories(request):
    categories = category.objects.annotate(service_count=Count('service'))
    return render(request, 'categories.html', {'categories': categories})


def services_page(request, id):
    services = service.objects.annotate(avg_rating=Avg('comments__rating')).filter(category=id)
    services_count = len(services)
    return render(request, 'services.html', {'services': services, 'services_count': services_count})


def service_page(request, id):
    serviceData = service.objects.annotate(
        avg_rating=Avg('comments__rating')).get(id=id)
    reviews = comments.objects.filter(service=serviceData.id)
    relateds = service.objects.annotate(avg_rating=Avg('comments__rating')).filter(
        category=serviceData.category.id).exclude(id=serviceData.id)
    return render(request, 'service.html', {'service': serviceData, 'reviews': reviews, 'relateds': relateds})


def book_service(request, id):
    if request.user.is_anonymous:
        return redirect('click:login')
    service_ = service.objects.get(id=id)
    return render(request, 'book-service.html', {'service': service_})


def book_service_insert(request, id):
    serviceData = service.objects.get(id=id)
    post = booking()
    post.date = request.POST.get('date')
    post.time = request.POST.get('time')
    post.location = request.POST.get('location')
    post.phn = request.POST.get('phone')
    post.service = serviceData
    post.user = request.user
    post.save()
    # messages.success(request, 'Booking Success')

    domain_url = 'http://localhost:8000/payment/'
    stripe.api_key = settings.STRIPE_SECRET_KEY
    try:
        checkout_session = stripe.checkout.Session.create(
            # new
            client_reference_id=request.user.id if request.user.is_authenticated else None,
            success_url=domain_url + \
            'success?session_id={CHECKOUT_SESSION_ID}',
            cancel_url=domain_url + 'cancelled/',
            payment_method_types=['card'],
            mode='payment',
            line_items=[
                {
                    'name': serviceData.title,
                    'quantity': 1,
                    'currency': 'inr',
                    'amount': str(serviceData.price) +'00',
                }
            ]
        )
        post.payment_id = checkout_session['payment_intent']
        post.save()
        request.session['checkout_session'] = checkout_session['id']
        # return JsonResponse({'sessionId': checkout_session['id']})
        return redirect('payments:payments')
    except Exception as e:
        print(str(e))
        # return JsonResponse({'error': str(e)})
        return redirect('/payment/cancelled/')


def cancel_booking(request):
    book = booking.objects.get(id=request.POST.get('booking_id'))
    book.reason = request.POST.get('reason')
    book.status = 'Canceled'
    book.save()
    messages.warning(request, 'Booking Canceled')
    if request.user.is_staff:
        return redirect('click:staff-bookings')
    else:
        return redirect('click:user-bookings')


def booking_status(request):
    book = booking.objects.get(id=request.POST.get('booking_id'))
    book.status = request.POST.get('status')
    book.save()
    messages.success(request, 'Status updated')
    if request.user.is_staff:
        return redirect('click:staff-bookings')
    else:
        return redirect('click:user-bookings')


def booking_comment(request):
    book = booking.objects.get(id=request.POST.get('booking_id'))
    serv = service.objects.get(id=request.POST.get('service_id'))
    comm = comments()
    comm.comment = request.POST.get('comment')
    comm.rating = request.POST.get('rate')
    comm.service = serv
    comm.booking = book
    comm.user = request.user
    comm.save()
    messages.success(request, 'Rating Posted Successfully')
    return redirect('click:user-bookings')


@user_passes_test(not_auth, 'click:user-dashboard', redirect_field_name='')
def loginView(request):
    return render(request, 'login.html')


def about(request):
    return render(request, 'about.html')


def contact(request):
    return render(request, 'contact.html')


# Authentication here.
def authLogin(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        if(user.is_superuser):
            return redirect('admin:index')
        else:
            return redirect('click:index')
    else:
        messages.error(request, 'Error Login')
        return redirect('click:login')


def authSignup(request):
    try:
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        user = User.objects.create_user(username, email, password)
        user.first_name = first_name
        user.last_name = last_name
        user.save()
        profil = profile()
        profil.dob = request.POST['date_of_birth']
        profil.mobile = request.POST['mob']
        profil.user = user
        profil.save()
        if user:
            login(request, user)
            return redirect('click:index')
        else:
            messages.error(request, 'Error Signup')
            return redirect('click:login')
    except:
        messages.error(request, 'Error Signup')
        return redirect('click:login')


def update_dp(request):
    pro = profile.objects.get(id=request.user.profile.id)
    pro.image = request.FILES.get('img')
    pro.save()
    if request.user.is_staff:
        return redirect('click:staff-profile')
    else:
        return redirect('click:user-profile')


def authLogout(request):
    logout(request)
    return redirect('click:index')


# User Routes
@login_required(login_url='click:login', redirect_field_name='')
def user(request):
    return redirect('click:user-dashboard')


@login_required(login_url='click:login', redirect_field_name='')
def userDashboard(request):
    bookings = booking.objects.filter(user=request.user)
    reviews = comments.objects.filter(user=request.user)
    bookings_count = len(bookings)
    reviews_count = len(reviews)
    return render(request, 'user/user-dashboard.html',{'bookings_count':bookings_count,'reviews_count':reviews_count})


@login_required(login_url='click:login', redirect_field_name='')
def userBooking(request):
    bookings = booking.objects.filter(user=request.user).order_by('-id')
    return render(request, 'user/user-booking.html', {'bookings': bookings})


@login_required(login_url='click:login', redirect_field_name='')
def userProfile(request):
    return render(request, 'user/user-profile.html')


@login_required(login_url='click:login', redirect_field_name='')
def userReviews(request):
    reviews = comments.objects.filter(user=request.user)
    return render(request, 'user/user-reviews.html', {'reviews': reviews})


# Staff Routes
@login_required(login_url='click:login', redirect_field_name='')
def staff(request):
    return redirect('click:staff-dashboard')


@login_required(login_url='click:login', redirect_field_name='')
def staffDashboard(request):
    bookings = booking.objects.filter(staff=request.user)
    bookings_count = len(bookings)
    return render(request, 'staff/staff-dashboard.html',{'bookings_count':bookings_count})


@login_required(login_url='click:login', redirect_field_name='')
def staffBooking(request):
    bookings = booking.objects.filter(staff=request.user).order_by('-id')
    return render(request, 'staff/staff-booking.html', {'bookings': bookings})


@login_required(login_url='click:login', redirect_field_name='')
def staffProfile(request):
    return render(request, 'staff/staff-profile.html')

click/templates/staff/staff-booking.html
{% extends "layouts/layout.html" %}

{% load extra_tags %}

{% block title %}User Dashboard{% endblock %}

{% block content %}

<div class="content">
    <div class="container">
        <div class="row">
            {% include 'includes/staff-dashboard-sidebar.html' %}
            <div class="col-xl-9 col-md-8">
                <div class="row align-items-center mb-4">
                    <div class="col">
                        <h4 class="widget-title mb-0">Booking List</h4>
                    </div>
                    <div class="col-auto">
                        <div class="sort-by">
                            <select class="form-control-sm custom-select searchFilter" id="status">
                                <option>All</option>
                                <option>Pending</option>
                                <option>Inprogress</option>
                                <option>Complete Request</option>
                                <option>Rejected</option>
                                <option>Cancelled</option>
                                <option>Completed</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div id="dataList">
                    {% for booking in bookings %}
                    <div class="bookings">
                        <div class="booking-list">
                            <div class="booking-widget">
                                <a href="{% url 'click:service' id=booking.service.id %}" class="booking-img">
                                    <img src="{{ booking.service.image.url }} " alt="{{ booking.service.title }}">
                                </a>
                                <div class="booking-det-info">
                                    <h3>
                                        <a
                                            href="{% url 'click:service' id=booking.service.id %}">{{ booking.service.title }}</a>
                                    </h3>
                                    <ul class="booking-details">
                                        <li>
                                            <span>Date</span> {{ booking.date }}
                                        </li>
                                        <li><span>Time</span> {{ booking.time }}</li>
                                        <li><span>Amount</span> ₹{{ booking.service.price }}</li>
                                        <li><span>Location</span> {{ booking.location }}</li>
                                        <li><span>Phone</span> {{ booking.phn }}</li>
                                        <li><span>User</span> {{ booking.user.first_name }}</li>
                                        <li><span>Booking Date</span> {{ booking.booking_date }}</li>
                                        <li><span>Status</span><span class="badge badge-pill badge-prof bg-success">
                                                {{ booking.status }}</span></li>
                                    </ul>
                                </div>
                            </div>

                            <div class="booking-action">
                                {% if booking.status == "Canceled" %}

                                <button type="button" data-reason="{{booking.reason}}" data-toggle="modal"
                                    data-target="#myReason" class="btn btn-sm bg-default-light"><i
                                        class="fas fa-info-circle"></i> Reason</button>

                                {% elif booking.status == "Pending" or booking.status == "Staff assigned" %}

                                <button type="button" data-id="{{booking.id}}" data-question="Updating Status to In Progress.." data-status="In progress" class="btn btn-sm bg-success-light mb-2"
                                    data-toggle="modal" data-target="#myStatus"><i class="fas fa-times"></i> In Progress</button>

                                <button type="button" data-id="{{booking.id}}" class="btn btn-sm bg-danger-light"
                                    data-toggle="modal" data-target="#myCancel"><i class="fas fa-times"></i> Cancel the
                                    Booking</button>

                                {% elif booking.status == "In progress" %}
                                <button type="button" data-id="{{booking.id}}" data-question="Updating Status to Completed.." data-status="Completed" class="btn btn-sm bg-success"
                                    data-toggle="modal" data-target="#myStatus"><i class="fas fa-check"></i> Completed</button>

                                {% endif %}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    {% comment %} <div class="pagination">
                        <ul>
                            <li class="active">
                                <a href="javascript:void(0);">1</a>
                            </li>
                            <li>
                                <a href="javascript:void(0);">2</a>
                            </li>
                            <li>
                                <a href="javascript:void(0);">3</a>
                            </li>
                            <li>
                                <a href="javascript:void(0);">4</a>
                            </li>
                            <li class="arrow">
                                <a href="javascript:void(0);"><i class="fas fa-angle-right"></i></a>
                            </li>
                        </ul>
                    </div> {% endcomment %}
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Reason Modal -->
<div class="modal fade" id="myReason" tabindex="-1" role="dialog" aria-labelledby="Reason" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myReasonTitle">Reason</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Cancel Modal -->
<div class="modal fade" id="myCancel" tabindex="-1" role="dialog" aria-labelledby="Cancel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myCancelLabel">Cancel</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="post" action="{% url 'click:cancel_booking' %}">
                {% csrf_token %}
                <div class="modal-body">
                    <input type="hidden" name="booking_id" class="booking_id">
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Reason:</label>
                        <textarea class="form-control" id="message-text" name="reason">Canceled by Staff : </textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Status Modal -->
<div class="modal fade" id="myStatus" tabindex="-1" role="dialog" aria-labelledby="Cancel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myStatusLabel">Warning</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="post" action="{% url 'click:booking_status' %}">
                {% csrf_token %}
                <div class="modal-body">
                    <input type="hidden" name="booking_id" class="booking_id">
                    <input type="hidden" name="status" class="status">
                    <p class="question"></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block script %}
<script>
    $('#myReason').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget)
        var reason = button.data('reason')
        var modal = $(this)
        modal.find('.modal-body').html(reason)
    })


    $('#myCancel').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget)
        var id = button.data('id')
        var modal = $(this)
        modal.find('.modal-body .booking_id').val(id)
    })

    $('#myStatus').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget)
        var id = button.data('id')
        var status = button.data('status')
        var question = button.data('question')
        var modal = $(this)
        modal.find('.modal-body .booking_id').val(id)
        modal.find('.modal-body .status').val(status)
        modal.find('.modal-body .question').html(question)
    })
</script>
{% endblock script %}

click/templates/staff/staff-dashboard.html
{% extends "layouts/layout.html" %}

{% block title %}User Dashboard{% endblock %}

{% block content %}

<div class="content">
    <div class="container">
        <div class="row">
            {% include 'includes/staff-dashboard-sidebar.html' %}
            <div class="col-xl-9 col-md-8">
                <h4 class="widget-title">Dashboard</h4>
                <div class="row">
                    <div class="col-lg-4">
                        <a href="{% url 'click:staff-bookings' %}" class="dash-widget dash-bg-1">
                            <span class="dash-widget-icon">{{bookings_count}}</span>
                            <div class="dash-widget-info">
                                <span>Bookings</span>
                            </div>
                        </a>
                    </div>
                    {% comment %} <div class="col-lg-4">
                        <a href="#" class="dash-widget dash-bg-2">
                            <span class="dash-widget-icon">66</span>
                            <div class="dash-widget-info">
                                <span>Services</span>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4">
                        <a href="#" class="dash-widget dash-bg-3">
                            <span class="dash-widget-icon">8</span>
                            <div class="dash-widget-info">
                                <span>Notification</span>
                            </div>
                        </a>
                    </div> {% endcomment %}
                </div>
                {% comment %} <div class="card mb-0">
                    <div class="row no-gutters">
                        <div class="col-lg-8">
                            <div class="card-body">
                                <h6 class="title">Plan Details</h6>
                                <div class="sp-plan-name">
                                    <h6 class="title">
                                        Gold <span class="badge badge-success badge-pill">Active</span>
                                    </h6>
                                    <p>Subscription ID: <span class="text-base">100394949</span></p>
                                </div>
                                <ul class="row">
                                    <li class="col-6 col-lg-6">
                                        <p>Started On 15 Jul, 2020</p>
                                    </li>
                                    <li class="col-6 col-lg-6">
                                        <p>Price $1502.00</p>
                                    </li>
                                </ul>
                                <h6 class="title">Last Payment</h6>
                                <ul class="row">
                                    <li class="col-sm-6">
                                        <p>Paid at 15 Jul 2020</p>
                                    </li>
                                    <li class="col-sm-6">
                                        <p><span class="text-success">Paid</span> <span class="amount">$1502.00</span>
                                        </p>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="sp-plan-action card-body">
                                <div class="mb-2">
                                    <a href="provider-subscription.html" class="btn btn-primary"><span>Change
                                            Plan</span></a>
                                </div>
                                <div class="next-billing">
                                    <p>Next Billing on <span>15 Jul, 2021</span></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div> {% endcomment %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

click/templates/staff/staff-profile.html
{% extends "layouts/layout.html" %}

{% block title %}User Dashboard{% endblock %}

{% block content %}

<div class="content">
    <div class="container">
        <div class="row">
            {% include 'includes/staff-dashboard-sidebar.html' %}
            <div class="col-xl-9 col-md-8">
                <div class="widget">
                    <h4 class="widget-title">Profile Settings</h4>
                    <div class="row">
                        <div class="col-xl-12">
                            <h5 class="form-title">Basic Information</h5>
                        </div>
                        <div class="form-group col-xl-12">
                            <div class="media align-items-center mb-3">
                                <img class="user-image" src="{{user.profile.image.url}}" alt="">
                                <div class="media-body">
                                    <h5 class="mb-0">{{user.first_name}} {{user.last_name}}</h5>
                                    <p>Max file size is 20mb</p>
                                    <form action="{% url 'click:dpupdate' %}" method="POST" id="dp"
                                        enctype="multipart/form-data">{% csrf_token %}
                                        <input type="file" name="img" onchange="$('#dp').submit()">
                                        {% comment %} <button type="submit">Upload</button> {% endcomment %}
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <form>
                    <div class="row">
                        <div class="form-group col-xl-6">
                            <label class="mr-sm-2">Name</label>
                            <input class="form-control" type="text" value="{{user.first_name}} {{user.last_name}}"
                                readonly>
                        </div>
                        <div class="form-group col-xl-6">
                            <label class="mr-sm-2">Email</label>
                            <input class="form-control" type="email" value="{{user.email}} " readonly>
                        </div>

                        <div class="form-group col-xl-6">
                            <label class="mr-sm-2">Mobile Number</label>
                            <input class="form-control no_only" type="text" value="{{user.profile.mobile}}" readonly
                                required>
                        </div>
                        <div class="form-group col-xl-6">
                            <label class="mr-sm-2">Date of birth</label>
                            <input type="text" class="form-control provider_datepicker" autocomplete="off"
                                value="{{user.profile.dob}}" readonly required>
                        </div>

                        {% comment %} <div class="form-group col-xl-12">
                            <button class="btn btn-primary pl-5 pr-5" type="submit">Update</button>
                        </div> {% endcomment %}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}