click/urls.py
"""
click URL Configuration
"""
from django.urls import path
from . import views

app_name = 'click'
urlpatterns = [
    path('', views.index, name='index'),
    path('categories/', views.categories, name='categories'),
    path('services/<int:id>', views.services_page, name='services'),
    path('service/<int:id>', views.service_page, name='service'),
    path('book-service/<int:id>', views.book_service, name='book-service'),
    path('book_service_insert/<int:id>', views.book_service_insert, name='book_service_insert'),
    path('about/', views.about, name='about'),
    path('login/', views.loginView, name='login'),
    path('contact/', views.contact, name='contact'),
    path('auth/login/', views.authLogin, name='auth-login'),
    path('auth/signup/', views.authSignup, name='auth-signup'),
    path('auth/logout/', views.authLogout, name='auth-logout'),
    path('user/', views.user, name='user'),
    path('user/dashboard', views.userDashboard, name='user-dashboard'),
    path('user/bookings', views.userBooking, name='user-bookings'),
    path('user/profile', views.userProfile, name='user-profile'),
    path('user/reviews', views.userReviews, name='user-reviews'),
    path('staff/', views.staff, name='staff'),
    path('staff/dashboard', views.staffDashboard, name='staff-dashboard'),
    path('staff/bookings', views.staffBooking, name='staff-bookings'),
    path('staff/profile', views.staffProfile, name='staff-profile'),
    path('dpupdate', views.update_dp, name='dpupdate'),
    path('cancel-booking', views.cancel_booking, name='cancel_booking'),
    path('status-update', views.booking_status, name='booking_status'),
    path('booking-comment', views.booking_comment, name='booking_comment'),
    
]

oneclick/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('click.urls')),
    path('payment/', include('payments.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns=urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

click/models.py
from django.db import models
from django.db import connections
from django.contrib.auth.models import User
from PIL import Image
from django.utils.timezone import now


class category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    featured = models.BooleanField(default=False)
    image = models.ImageField(upload_to='category', default='SOME STRING')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Categories"


class service(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='service', default='SOME STRING')
    description = models.TextField()
    feature = models.CharField(max_length=200)
    price = models.IntegerField(default=10)
    category = models.ForeignKey(category,  on_delete=models.CASCADE)
    featured = models.BooleanField(default=False)
    visible = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class booking(models.Model):
    booking_date = models.DateTimeField(auto_now_add=True, editable=False)
    date = models.DateField(default=now,blank=True, null=True)
    time = models.TimeField(default=now)
    location = models.TextField()
    phn = models.BigIntegerField(verbose_name="Phone Number")
    staff = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='staff', null=True, blank=True)
    status = models.CharField(max_length=256, default='Pending', choices=[('Pending', 'Pending'), (
        'Staff assigned', 'Staff assigned'), ('In progress', 'In progress'), ('Completed', 'Completed'), ('Canceled', 'Canceled')])
    service = models.ForeignKey(service, on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='user')
    reason= models.TextField(null=True,blank=True)
    payment_id = models.TextField(default='nil')

    def __str__(self):
        return f"{self.user.first_name} - {self.service.title}"



class comments(models.Model):
    comment = models.TextField()
    rating = models.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    service = models.ForeignKey(service, on_delete=models.CASCADE)
    booking = models.OneToOneField(booking, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Review"

class profile(models.Model):
    image = models.ImageField(upload_to='profile', default='profile/profile.png')
    mobile = models.BigIntegerField(verbose_name="Phone Number")
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob=models.DateField(default=now,blank=True, null=True)
    

click/views.py
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.db.models.aggregates import Avg
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from .models import *
from django.db.models import Count
from django.contrib import messages
import stripe

# Test Functions


def not_auth(user):
    return not user.is_authenticated


def is_staff(user):
    return user.is_staff


# Create your views here.
def index(request):
    categories = category.objects.filter(
        featured=1).annotate(service_count=Count('service'))
    services = service.objects.filter(featured=1)
    return render(request, 'index.html', {'categories': categories, 'services': services})


def categories(request):
    categories = category.objects.annotate(service_count=Count('service'))
    return render(request, 'categories.html', {'categories': categories})


def services_page(request, id):
    services = service.objects.annotate(avg_rating=Avg('comments__rating')).filter(category=id)
    services_count = len(services)
    return render(request, 'services.html', {'services': services, 'services_count': services_count})


def service_page(request, id):
    serviceData = service.objects.annotate(
        avg_rating=Avg('comments__rating')).get(id=id)
    reviews = comments.objects.filter(service=serviceData.id)
    relateds = service.objects.annotate(avg_rating=Avg('comments__rating')).filter(
        category=serviceData.category.id).exclude(id=serviceData.id)
    return render(request, 'service.html', {'service': serviceData, 'reviews': reviews, 'relateds': relateds})


def book_service(request, id):
    if request.user.is_anonymous:
        return redirect('click:login')
    service_ = service.objects.get(id=id)
    return render(request, 'book-service.html', {'service': service_})


def book_service_insert(request, id):
    serviceData = service.objects.get(id=id)
    post = booking()
    post.date = request.POST.get('date')
    post.time = request.POST.get('time')
    post.location = request.POST.get('location')
    post.phn = request.POST.get('phone')
    post.service = serviceData
    post.user = request.user
    post.save()
    # messages.success(request, 'Booking Success')

    domain_url = 'http://localhost:8000/payment/'
    stripe.api_key = settings.STRIPE_SECRET_KEY
    try:
        checkout_session = stripe.checkout.Session.create(
            # new
            client_reference_id=request.user.id if request.user.is_authenticated else None,
            success_url=domain_url + \
            'success?session_id={CHECKOUT_SESSION_ID}',
            cancel_url=domain_url + 'cancelled/',
            payment_method_types=['card'],
            mode='payment',
            line_items=[
                {
                    'name': serviceData.title,
                    'quantity': 1,
                    'currency': 'inr',
                    'amount': str(serviceData.price) +'00',
                }
            ]
        )
        post.payment_id = checkout_session['payment_intent']
        post.save()
        request.session['checkout_session'] = checkout_session['id']
        # return JsonResponse({'sessionId': checkout_session['id']})
        return redirect('payments:payments')
    except Exception as e:
        print(str(e))
        # return JsonResponse({'error': str(e)})
        return redirect('/payment/cancelled/')


def cancel_booking(request):
    book = booking.objects.get(id=request.POST.get('booking_id'))
    book.reason = request.POST.get('reason')
    book.status = 'Canceled'
    book.save()
    messages.warning(request, 'Booking Canceled')
    if request.user.is_staff:
        return redirect('click:staff-bookings')
    else:
        return redirect('click:user-bookings')


def booking_status(request):
    book = booking.objects.get(id=request.POST.get('booking_id'))
    book.status = request.POST.get('status')
    book.save()
    messages.success(request, 'Status updated')
    if request.user.is_staff:
        return redirect('click:staff-bookings')
    else:
        return redirect('click:user-bookings')


def booking_comment(request):
    book = booking.objects.get(id=request.POST.get('booking_id'))
    serv = service.objects.get(id=request.POST.get('service_id'))
    comm = comments()
    comm.comment = request.POST.get('comment')
    comm.rating = request.POST.get('rate')
    comm.service = serv
    comm.booking = book
    comm.user = request.user
    comm.save()
    messages.success(request, 'Rating Posted Successfully')
    return redirect('click:user-bookings')


@user_passes_test(not_auth, 'click:user-dashboard', redirect_field_name='')
def loginView(request):
    return render(request, 'login.html')


def about(request):
    return render(request, 'about.html')


def contact(request):
    return render(request, 'contact.html')


# Authentication here.
def authLogin(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        if(user.is_superuser):
            return redirect('admin:index')
        else:
            return redirect('click:index')
    else:
        messages.error(request, 'Error Login')
        return redirect('click:login')


def authSignup(request):
    try:
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        user = User.objects.create_user(username, email, password)
        user.first_name = first_name
        user.last_name = last_name
        user.save()
        profil = profile()
        profil.dob = request.POST['date_of_birth']
        profil.mobile = request.POST['mob']
        profil.user = user
        profil.save()
        if user:
            login(request, user)
            return redirect('click:index')
        else:
            messages.error(request, 'Error Signup')
            return redirect('click:login')
    except:
        messages.error(request, 'Error Signup')
        return redirect('click:login')


def update_dp(request):
    pro = profile.objects.get(id=request.user.profile.id)
    pro.image = request.FILES.get('img')
    pro.save()
    if request.user.is_staff:
        return redirect('click:staff-profile')
    else:
        return redirect('click:user-profile')


def authLogout(request):
    logout(request)
    return redirect('click:index')


# User Routes
@login_required(login_url='click:login', redirect_field_name='')
def user(request):
    return redirect('click:user-dashboard')


@login_required(login_url='click:login', redirect_field_name='')
def userDashboard(request):
    bookings = booking.objects.filter(user=request.user)
    reviews = comments.objects.filter(user=request.user)
    bookings_count = len(bookings)
    reviews_count = len(reviews)
    return render(request, 'user/user-dashboard.html',{'bookings_count':bookings_count,'reviews_count':reviews_count})


@login_required(login_url='click:login', redirect_field_name='')
def userBooking(request):
    bookings = booking.objects.filter(user=request.user).order_by('-id')
    return render(request, 'user/user-booking.html', {'bookings': bookings})


@login_required(login_url='click:login', redirect_field_name='')
def userProfile(request):
    return render(request, 'user/user-profile.html')


@login_required(login_url='click:login', redirect_field_name='')
def userReviews(request):
    reviews = comments.objects.filter(user=request.user)
    return render(request, 'user/user-reviews.html', {'reviews': reviews})


# Staff Routes
@login_required(login_url='click:login', redirect_field_name='')
def staff(request):
    return redirect('click:staff-dashboard')


@login_required(login_url='click:login', redirect_field_name='')
def staffDashboard(request):
    bookings = booking.objects.filter(staff=request.user)
    bookings_count = len(bookings)
    return render(request, 'staff/staff-dashboard.html',{'bookings_count':bookings_count})


@login_required(login_url='click:login', redirect_field_name='')
def staffBooking(request):
    bookings = booking.objects.filter(staff=request.user).order_by('-id')
    return render(request, 'staff/staff-booking.html', {'bookings': bookings})


@login_required(login_url='click:login', redirect_field_name='')
def staffProfile(request):
    return render(request, 'staff/staff-profile.html')

click/templates/categories.html
{% extends "layouts/layout.html" %}

{% block title %}Categories{% endblock %}

{% block content %}

<!-- Breadcrumb -->
<div class="breadcrumb-bar">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="breadcrumb-title">
                    <h2>Categories</h2>
                </div>
            </div>
            <div class="col-auto float-right ml-auto breadcrumb-menu">
                <nav aria-label="breadcrumb" class="page-breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="index-2.html">Home</a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">Categories</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- /Breadcrumb -->

<div class="content">
    <div class="container">
        <div class="catsec clearfix">
            <div class="row">
                {% for category in categories %}
                <div class="col-lg-4 col-md-6">
                    <a href="{% url 'click:services' id=category.id %}">
                        <div class="cate-widget">
                            <img src="{{category.image.url}}" alt="">
                            <div class="cate-title">
                                <h3><span><i class="fas fa-circle"></i>{{category.title}}</span></h3>
                            </div>
                            <div class="cate-count">
                                <i class="fas fa-clone"></i> {{ category.service_count }}
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
                
            {% comment %} <div class="pagination">
                <ul>
                    <li class="active"><a href="javascript:void(0);">1</a></li>
                    <li><a href="javascript:void(0);">2</a></li>
                    <li><a href="javascript:void(0);">3</a></li>
                    <li><a href="javascript:void(0);">4</a></li>
                    <li class="arrow"><a href="javascript:void(0);"><i class="fas fa-angle-right"></i></a></li>
                </ul>
            </div> {% endcomment %}
        </div>
    </div>
</div>
{% endblock content %}

click/templates/index.html
{% extends "layouts/layout.html" %}

{% load extra_tags %}

{% block title %}One Click{% endblock %}

{% block content %}
<!-- Hero Section -->
<section class="hero-section">
    <div class="layer">
        <div class="home-banner"></div>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-12">
                    <div class="section-search">
                        <h3>Welcome to <span>OneClick</span></h3>
                        <p>We provide you with the best services</p>
                        {% comment %} <div class="search-box">
                            <form action="https://OneClick-html.dreamguystech.com/">
                                <div class="search-input line">
                                    <i class="fas fa-tv bficon"></i>
                                    <div class="form-group mb-0">
                                        <input type="text" class="form-control" placeholder="What are you looking for?">
                                    </div>
                                </div>
                                <div class="search-input">
                                    <i class="fas fa-location-arrow bficon"></i>
                                    <div class="form-group mb-0">
                                        <input type="text" class="form-control" placeholder="Your Location">
                                        <a class="current-loc-icon current_location" href="javascript:void(0);"><i
                                                class="fas fa-crosshairs"></i></a>
                                    </div>
                                </div>
                                <div class="search-btn">
                                    <button class="btn search_service" type="submit">Search</button>
                                </div>
                            </form>
                        </div> {% endcomment %}
                        {% comment %} <div class="search-cat">
                            <i class="fas fa-circle"></i>
                            <span>Popular Searches</span>
                            <a href="{% url 'click:services' %}">Electrical Works</a>
                            <a href="{% url 'click:services' %}">Cleaning</a>
                            <a href="{% url 'click:services' %}">AC Repair</a>
                        </div> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- /Hero Section -->

<!-- Category Section -->
<section class="category-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="row">
                    <div class="col-md-6">
                        <div class="heading">
                            <h2>Featured Categories</h2>
                            <span>What do you need to find?</span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="viewall">
                            <h4><a href="{% url 'click:categories' %}">View All <i class="fas fa-angle-right"></i></a>
                            </h4>
                            <span>Featured Categories</span>
                        </div>
                    </div>
                </div>
                <div class="catsec">
                    <div class="row">
                        {% for category in categories %}
                        <div class="col-lg-4 col-md-6">
                            <a href="{% url 'click:services' id=category.id %}">
                                <div class="cate-widget">
                                    <img src="{{ category.image.url }}" alt=" {{ category.title }}">
                                    <div class="cate-title">
                                        <h3><span><i class="fas fa-circle"></i> {{ category.title }}</span></h3>
                                    </div>
                                    <div class="cate-count">
                                        <i class="fas fa-clone"></i> {{ category.service_count }}
                                    </div>
                                </div>
                            </a>
                        </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- /Category Section -->

<!-- How It Works -->
{% include 'includes/works.html' %}
<!-- /How It Works -->

<!-- Popular Servides -->
<section class="popular-services">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="row">
                    <div class="col-md-6">
                        <div class="heading">
                            <h2>Most Popular Services</h2>
                            <span>Explore the greates our services. You won’t be disappointed</span>
                        </div>
                    </div>
                    {% comment %} <div class="col-md-6">
                        <div class="viewall">
                            <h4><a href="categories.html">View All <i class="fas fa-angle-right"></i></a></h4>
                            <span>Most Popular</span>
                        </div>
                    </div> {% endcomment %}
                </div>
                <div class="service-carousel">
                    <div class="service-slider owl-carousel owl-theme">
                        {% for service in services %}
                        <div class="service-widget">
                            <div class="service-img">
                                <a href="{% url 'click:service' id=service.id %}">
                                    <img class="img-fluid serv-img" alt="Service Image" src="{{service.image.url}}">
                                </a>
                                <div class="item-info">
                                    <div class="service-user">
                                        <span class="service-price">₹{{service.price}}</span>
                                    </div>
                                    <div class="cate-list">
                                        <a class="bg-yellow"
                                            href="{% url 'click:service' id=service.id %}">{{service.category.title}}</a>
                                    </div>
                                </div>
                            </div>
                            <div class="service-content">
                                <h3 class="title">
                                    <a href="{% url 'click:service' id=service.id %}">{{service.title}}</a>
                                </h3>
                                <div class="rating">
                                    {% for i in service.avg_rating|times %}
                                    <i class="fas fa-star filled"></i>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- /Popular Servides -->

{% endblock %}

click/templates/login.html
{% extends "layouts/layout.html" %}

{% block title %}Login{% endblock %}

{% block content %}

<!-- Breadcrumb -->
<div class="breadcrumb-bar">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="breadcrumb-title">
                    <h2>Login</h2>
                </div>
            </div>
            <div class="col-auto float-right ml-auto breadcrumb-menu">
                <nav aria-label="breadcrumb" class="page-breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="index-2.html">Home</a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">Login</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- /Breadcrumb -->

<div class="content">
    <div class="container">
        <div class="catsec clearfix">
            <div class="row">
                <div class="col-md-12">
                    <div class="login-header">
                        <h3>Login <span>OneClick</span></h3>
                    </div>
                    <form action="{% url 'click:auth-login' %}" method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group form-focus">
                                    <label class="focus-label">Username</label>
                                    <input type="text" name="username" class="form-control"
                                        placeholder="username" required>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group form-focus">
                                    <label class="focus-label">Password</label>
                                    <input type="password" name="password" class="form-control" placeholder="********" required>
                                </div>
                            </div>
                        </div>
                        <button class="btn btn-primary btn-lg login-btn" type="submit">Login</button>
                        <div class="text-left">
                            <a class="forgot-link" href="#">Forgot your password?</a>
                        </div>
                    </form>
                    <div class="login-or"> <span class="or-line"></span>
                        <span class="span-or">or</span>
                    </div>
                    <div class="login-header">
                        <h3>Join as a User</h3>
                    </div>
                    <form action="{% url 'click:auth-signup' %}" method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group form-focus">
                                    <label class="focus-label">First Name</label>
                                    <input type="text" name="first_name" class="form-control" placeholder="John" required>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group form-focus">
                                    <label class="focus-label">Last Name</label>
                                    <input type="text" name="last_name" class="form-control" placeholder="Doe" required>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group form-focus">
                                    <label class="focus-label">Username</label>
                                    <input type="text" name="username" class="form-control" placeholder="johndoe" required>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group form-focus">
                                    <label class="focus-label">Email</label>
                                    <input type="email" name="email" class="form-control" placeholder="johndoe@example.com" required>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group form-focus">
                                    <label class="focus-label">Mobile Number</label>
                                    <input type="text" name="mob" class="form-control" placeholder="986 452 1236" maxlength="10" minlength="10" autocomplete="off" required>
                                </div>
                            </div>
                            
                            <div class="col-md-6">
                                <div class="form-group form-focus">
                                    <label class="focus-label">DOB</label>
                                    <input class="form-control datepicker " type="text" name="date_of_birth" autocomplete="off" required>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group form-focus">
                                    <label class="focus-label">Create Password</label>
                                    <input type="password" name="password" class="form-control" maxlength="6" minlength="30" placeholder="********" required>
                                </div>
                            </div>
                        </div>
                        <button class="btn btn-primary btn-lg login-btn" type="submit">Signup</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block script %}
<script>
    $(function () {
        $(".datepicker").datetimepicker({
            timepicker: false,
            format: 'Y-m-d',
            maxDate: new Date()
        });
    });
</script>
{% endblock script %}